level_delete:
    pattern:  /levels/{id}/delete
    defaults: {_controller: SykesGuideBundle:Level:delete}
    
level_list:
    pattern:  /levels
    defaults: {_controller: SykesGuideBundle:Level:index}
    
category_delete:
    pattern:  /categories/{id}/delete
    defaults: {_controller: SykesGuideBundle:Category:delete}

category_edit:
    pattern:  /categories/{id}/edit
    defaults: {_controller: SykesGuideBundle:Category:index}
    
category_list:
    pattern:  /categories
    defaults: {_controller: SykesGuideBundle:Category:index}
    
answer_delete:
    pattern:  /answers/{id}/delete
    defaults: {_controller: SykesGuideBundle:Answer:delete}

answer_edit:
    pattern:  /answers/{id}/edit
    defaults: {_controller: SykesGuideBundle:Answer:edit}
    
question_delete:
    pattern:  /questions/{id}/delete
    defaults: {_controller: SykesGuideBundle:Question:delete}
    
question_edit_answer:
    pattern:  /questions/{id}/edit-answer/{answer_id}
    defaults: {_controller: SykesGuideBundle:Question:view}

question_edit:
    pattern:  /questions/{id}/edit
    defaults: {_controller: SykesGuideBundle:Question:index}

question_view:
    pattern:  /questions/{id}
    defaults: {_controller: SykesGuideBundle:Question:view}
    
question_list:
    pattern:  /questions
    defaults: {_controller: SykesGuideBundle:Question:index}