parameters:
#    sykes_guide.example.class: Sykes\GuideBundle\Example

services:
#    sykes_guide.example:
#        class: %sykes_guide.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
