
WGWebsiteBundle:
    resource: "@WGWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

#SykesCBIGuideBundle:
#    resource: "@SykesCBIGuideBundle/Resources/config/routing.yml"
#    prefix:   /
