home:
    pattern:  /
    defaults: { _controller: SykesWebsiteBundle:Default:index }

login:
    pattern:  /login
    defaults: { _controller: SykesWebsiteBundle:Default:login }

login_check:
    pattern:  /login_check

logout:
    pattern:  /logout
